services:
  database:
    tty: true
    image: postgres:15
    restart: on-failure
    env_file:
      - .env
    volumes:
      - pg_habits_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  django_app:
    tty: true
    build: .
    volumes:
      - static:/static/
    env_file:
      - .env
    depends_on:
      database:
        condition:
          service_healthy
    command: sh -c "python manage.py migrate && python manage.py collectstatic --no-input && gunicorn -w $(( $(nproc)*2+1 )) -b 0.0.0.0:5000 config.wsgi"
  broker:
    tty: true
    image: redis
    restart: on-failure
    expose:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10
  celery:
    tty: true
    build: .
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - broker
    command: celery -A config worker -l INFO

  celery-beat:
    tty: true
    build: .
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - broker
      - django_app
      - celery
    command: celery -A config beat -l info
  nginx:
    tty: true
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - static:/static/
    depends_on:
      - django_app
volumes:
  pg_habits_data:
    driver: local
  static:
    driver: local